name: fwfh_cached_network_image
version: 0.14.2
publish_to: "none"
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/Fares-ayman-farouk/flutter_widget_from_html

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  cached_network_image:
    git:
      url: https://github.com/SaadSabry/flutter_cached_network_image.git
      path: cached_network_image
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/SaadSabry/flutter_cache_manager.git
      path: flutter_cache_manager
  flutter_widget_from_html_core: ">0.8.0 <0.15.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: ^1.0.0

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - img
  - fwfh
